# Настройка сообщений.
messages:
  # Сообщение для консоли при неправильном использовании
  console_error: "Консоль не может использовать эту команду без аргументов."
  # Сообщение о недостатке прав для других игроков
  no_permission_others: "У вас нет прав на выполнение этой команды для другого игрока."
  # Сообщение об ошибке при неверном использовании команды
  wrong_usage: "Использование: %usage%"
  # Сообщение при отсутствии кастомных рецептов
  no_recipes: "Не найдено кастомных рецептов в CMI."
  # Сообщение при неверном имени игрока
  player_not_found: "Игрок не найден: %player%"

# Здесь можно настроить внешний вид главного меню и меню деталей рецепта
gui-pattern:
  # Настройки главного меню (список рецептов)
  main-menu:
    # Заголовок GUI
    title: "Кастомные крафты"
    # Количество строк (1-6)
    rows: 6
    # Lore для иконки рецепта
    lore:
      - "§e➥ §fНажмите, чтобы посмотреть"
    # Паттерн отображения
    # 'R' — слот для рецепта
    # '-' — пустой слот
    pattern:
      - "----------"
      - "--RRRRRR--"
      - "--RRRRRR--"
      - "--RRRRRR--"
      - "--RRRRRR--"
      - "----------"

  # Настройки меню деталей рецепта (3x3 сетка + результат + кнопка "Назад")
  detail-menu:
    # Заголовок GUI
    title: "Просмотр крафта"
    # Количество строк (1-6)
    rows: 6
    # Настройки кнопки "Назад"
    back-button:
      # Материал иконки (например, BARRIER, BOOK, и т.д.)
      material: "ARROW"
      # Название иконки
      name: "§cВернуться назад"
      # Описание иконки (lore)
      lore: [ ]
    # Паттерн отображения
    # 'I' — слот ингредиента (3x3 сетка)
    # 'R' — слот результата
    # 'B' — слот кнопки "Назад"
    # '-' — пустой слот
    recipe-pattern:
      - "----------"
      - "--III-----"
      - "--III--R--"
      - "--III-----"
      - "----------"
      - "----B-----"