# Message configuration.
messages:
  # Message for console when using command incorrectly
  console_error: "Console cannot use this command without arguments."
  # Message for lacking permission to use command on other players
  no_permission_others: "You don't have permission to use this command on other players."
  # Message for incorrect command usage
  wrong_usage: "Usage: %usage%"
  # Message when no custom recipes are found
  no_recipes: "No custom recipes found in CMI."
  # Message for invalid player name
  player_not_found: "Player not found: %player%"

# Configure the appearance of main menu and recipe detail menu
gui-pattern:
  # Main menu settings (recipe list)
  main-menu:
    # GUI title
    title: "Custom Crafts"
    # Number of rows (1-6)
    rows: 6
    # Lore for recipe icon
    lore:
      - "§e➥ §fClick to view"
    # Display pattern
    # 'R' - slot for recipe
    # '-' - empty slot
    pattern:
      - "----------"
      - "--RRRRRR--"
      - "--RRRRRR--"
      - "--RRRRRR--"
      - "--RRRRRR--"
      - "----------"

  # Recipe detail menu settings (3x3 grid + result + back button)
  detail-menu:
    # GUI title
    title: "View Craft"
    # Number of rows (1-6)
    rows: 6
    # Back button settings
    back-button:
      # Icon material (e.g., BARRIER, BOOK, etc.)
      material: "ARROW"
      # Icon name
      name: "§cGo Back"
      # Icon description (lore)
      lore: [ ]
    # Display pattern
    # 'I' - ingredient slot (3x3 grid)
    # 'R' - result slot
    # 'B' - back button slot
    # '-' - empty slot
    recipe-pattern:
      - "----------"
      - "--III-----"
      - "--III--R--"
      - "--III-----"
      - "----------"
      - "----B-----"