# Конфигурация GUI для плагина CMIRecipes
# Здесь можно настроить внешний вид главного меню и меню деталей рецепта

gui-pattern:
  # Настройки главного меню (список рецептов)
  main-menu:
    # Заголовок GUI
    title: "Кастомные крафты"
    # Количество строк (1-6)
    rows: 6
    # Lore для иконки рецепта
    lore:
      - "§e➥ §fНажмите, чтобы посмотреть"
    # Паттерн отображения
    # 'R' — слот для рецепта
    # '-' — пустой слот
    pattern:
      - "----------"
      - "--RRRRRR--"
      - "--RRRRRR--"
      - "--RRRRRR--"
      - "--RRRRRR--"
      - "----------"

  # Настройки меню деталей рецепта (3x3 сетка + результат + кнопка "Назад")
  detail-menu:
    # Заголовок GUI
    title: "Просмотр крафта"
    # Количество строк (1-6)
    rows: 6
    # Настройки кнопки "Назад"
    back-button:
      # Материал иконки (например, BARRIER, BOOK, и т.д.)
      material: "ARROW"
      # Название иконки
      name: "§cВернуться назад"
      # Описание иконки (lore)
      lore: { }
    # Паттерн отображения
    # 'I' — слот ингредиента (3x3 сетка)
    # 'R' — слот результата
    # 'B' — слот кнопки "Назад"
    # '-' — пустой слот
    recipe-pattern:
      - "----------"
      - "--III-----"
      - "--III--R--"
      - "--III-----"
      - "----------"
      - "----B-----"