name: CMIRecipes
version: '1.0.0'
main: me.seetch.cmirecipes.CMIRecipes
api-version: '1.20'
authors: [ seetch ]
depend:
  - CMI
commands:
  cmirecipes:
    description: View all custom recipes from CMI
    usage: /cmirecipes [player]
    permission: cmirecipes.use
    aliases:
      - crafts
      - recipes
permissions:
  cmirecipes.use:
    description: Allows using the command for yourself
    default: true
  cmirecipes.others:
    description: Allows using the command for another player
    default: op